"""Domain layer - Models and business rules."""
from .models import (
    Athlete,
    ATRConfig,
    Biometria,
    BloqueATR,
    Ejercicio,
    Equipamiento,
    GastoEnergetico,
    Macros,
    Nivel,
    NutricionPlan,
    Objetivo,
    ProgramaCompleto,
    SemanaEntrenamiento,
    SesionEntrenamiento,
    Sexo,
    TrainingContext,
)
from .rules import (
    ATR_CONFIGS,
    PATRONES_POR_SESION,
    SEMANAS_DELOAD,
    SPLITS,
    calcular_gasto,
    calcular_imc,
    calcular_macros,
    es_semana_deload,
    estimar_agua,
    estimar_grasa,
    generar_estrategia_nutricional,
    generar_estrategias_neat,
    generar_intro_neat,
    obtener_bloque_desde_semana,
    obtener_config_semana,
    obtener_patrones_sesion,
    obtener_split,
)

__all__ = [
    # Models
    "Athlete",
    "Biometria",
    "BloqueATR",
    "Equipamiento",
    "GastoEnergetico",
    "Macros",
    "Nivel",
    "NutricionPlan",
    "Objetivo",
    "ProgramaCompleto",
    "SesionEntrenamiento",
    "Sexo",
    "SemanaEntrenamiento",
    "TrainingContext",
    "Ejercicio",
    "ATRConfig",
    # Rules
    "calcular_imc",
    "calcular_macros",
    "calcular_gasto",
    "estimar_grasa",
    "estimar_agua",
    "obtener_bloque_desde_semana",
    "obtener_config_semana",
    "obtener_split",
    "obtener_patrones_sesion",
    "es_semana_deload",
    "generar_estrategia_nutricional",
    "generar_intro_neat",
    "generar_estrategias_neat",
    "ATR_CONFIGS",
    "SEMANAS_DELOAD",
    "SPLITS",
    "PATRONES_POR_SESION",
]
